version: "3.9"
services:
  postgres-server:
    networks:
      - default
    build:
      context: ./
      dockerfile: Dockerfile-postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 60s
      retries: 3
      start_period: 10s

  application-war:
    networks:
      - default
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
networks:
  default:
    driver: bridge